import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ProblemContextProvider } from './context'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div>
      <ProblemContextProvider>{children}</ProblemContextProvider>
    </div>
  )
}
