import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from './_components/theme-provider'
import NavBar from './_components/nav-bar'
import AuthenticationProvider from '../providers/auth-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="m-0 flex h-full w-full flex-col gap-y-4 p-0">
            <NavBar />
            <AuthenticationProvider>{children}</AuthenticationProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
