import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Stuck Overflow - Problems',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="max-w-screen-2xl m-0 p-0 h-full flex flex-col gap-y-4">
      {children}
    </div>
  )
}
