import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Stuck Overflow - Problems',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return <div className="m-0 flex h-full flex-col gap-y-2 p-0">{children}</div>
}
